### ISSUE TITLE
Delivering result of network call to another activity.

### ISSUE THREAD

**Issue by nilkashid** [foxykeep/DataDroid#28]
First off all this is not an issue regarding our datadaroid library. But I just wanted to ask something that's why open new issue 

So What I want to do I want to make a network call and and i want to go to new another activity. So what right now is going on after completion of request it will deliver result to calling activity. 
So what I want to do I want to deliver that result directly to my newly open activity. Is it possible with data droid.
What i feel when we do "request.execute(request, requestlistener)" If I pass listener which is define in newly created activity then it is possible to deliver result to new activity. 

Is it really possible. Or is there any other way to do that.
Need Help to solve this problem. How can do it with my costume event. Any idea? Need help. thank you .

**Comment by Maragues** [comment]
I suggest sending a Broadcast Intent from the operation and registering a BroadcastReceiver in the activity.

Anyway, this is more a StackOverflow question.

**Comment by foxykeep** [comment]
Multiple way to resolve this issue (dunno which one is the best for your case)
- Wait for the response on the first activity and pass the returned object(s) as Parcelable in the Intent to the second activity
- Do the request call on the second activity
- Use a broadcast receiver as Maragues said. Only issue with this solution is that the operation may already be finished by the time the 2nd activity is done loading (and in this case you'll never get the broadcast)
- Make the call in the first activity, launch the second activity and make again the same call. (WARNING !! same problem as the previous one. the request may already be finished and in this case you'll do a whole new request instead of adding yourself as a listener to it)

From my point of view the best solution is either the first or the second one. 3 and 4 are hackish....

(I also agree that's more a StackOverflow question)
