### ISSUE TITLE
Bug: no recycling of HttpClient

### ISSUE THREAD

**Issue by saik0** [foxykeep/DataDroid#6]
we should setup the HttpClient in one pass and allow the user to store and recycle it.

**Comment by saik0** [comment]
Ah, AndroidHtpClient new(instance) returns an HttpClient, but none of our retrieveResponseFromService() methods take one as a paramater. Should be easy enough.

**Comment by foxykeep** [comment]
As said on the other bugs, I'm currently rewriting NetworkConnection to make it more usable and fix some issues and I'll try to find a way to be able to recycle the client. 
The main problem is that 90% of the time it will have a lot of changes. Especially since depending on the Android version we shouldn't always use an HttpClient. (Starting with GingerBread, the Android team recommends to use HTTPUrlConnection.  I'm currently working on changing that seemlessly for the developer http://android-developers.blogspot.fr/2011/09/androids-http-clients.html)

**Comment by foxykeep** [comment]
Datadroid v2 now uses URLHttpConnection. so the recycling is not anymore needed
